version: '3'
services:
  app:
    build:
      context: .
    restart: always
    container_name: relay_switch_app
    environment:
      - HLK_SW16_HOST=192.168.0.200
      - HLK_SW16_PORT=8080
      - APP_PORT=8082
      - GIN_MODE=release
    ports:
      - 8082:8082
    tty: true